// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpdlV8yMicWNeV4MUVDpxb5sH7HJAsQjw',
    appId: '1:676805655287:web:679e9164e081dfc66831f2',
    messagingSenderId: '676805655287',
    projectId: 'recipe-finder-12a1b',
    authDomain: 'recipe-finder-12a1b.firebaseapp.com',
    storageBucket: 'recipe-finder-12a1b.firebasestorage.app',
    measurementId: 'G-0E35CHE1S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1hiZnSIE2LTif7nPW95wu1kPyx91aYQ',
    appId: '1:676805655287:android:d9157782dd0526916831f2',
    messagingSenderId: '676805655287',
    projectId: 'recipe-finder-12a1b',
    storageBucket: 'recipe-finder-12a1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0VWOYtbdKnCButOeqLrFl_e_9IKE9yM',
    appId: '1:676805655287:ios:bd993bf50c08f6426831f2',
    messagingSenderId: '676805655287',
    projectId: 'recipe-finder-12a1b',
    storageBucket: 'recipe-finder-12a1b.firebasestorage.app',
    iosClientId: '676805655287-5rie7u05ecb29ankm565iamk645hqopi.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0VWOYtbdKnCButOeqLrFl_e_9IKE9yM',
    appId: '1:676805655287:ios:bd993bf50c08f6426831f2',
    messagingSenderId: '676805655287',
    projectId: 'recipe-finder-12a1b',
    storageBucket: 'recipe-finder-12a1b.firebasestorage.app',
    iosClientId: '676805655287-5rie7u05ecb29ankm565iamk645hqopi.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpdlV8yMicWNeV4MUVDpxb5sH7HJAsQjw',
    appId: '1:676805655287:web:fd49169c622321046831f2',
    messagingSenderId: '676805655287',
    projectId: 'recipe-finder-12a1b',
    authDomain: 'recipe-finder-12a1b.firebaseapp.com',
    storageBucket: 'recipe-finder-12a1b.firebasestorage.app',
    measurementId: 'G-56GFGL1FPC',
  );
}
